project:
  name: @project.name@
  version: @project.version@
my:
  base:
    request-log-enable: true
    thread-prefix: @project.name@+"_"
    slow-sql-log-enable: false
    sql-log-enable: true
server:
  port: 8088
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3308/xxx?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  data:
    redis:
      database: 5
      host: xxx
      port: 6380
      password: Ah8mm6tgE0vSv2aadIELqdHAAohgbFYl
      lettuce:
        pool:
          max-active: 20
          max-idle: 8
          max-wait: 5000ms
          min-idle: 1
      timeout: 30s
  cloud:
    nacos:
      server-addr: xxx
      username: nacos
      password: OrbD7NI7ihgVL1a6lYvLGSdmvYX0OFSm
      config:
        namespace: test
        file-extension: yaml
        import-check:
          enabled: false
      discovery:
        namespace: test
        service: base-starter
        ip: xxx
  rabbitmq:
    # 动态创建和绑定队列、交换机的配置
    modules:
      # 正常队列
      - routing-key: test
        consumer: testConsumerService
        producer: testProducerService
        autoAck: false
        queue:
          name: test
          dead-letter-exchange: dead
          dead-letter-routing-key: dead
          arguments:
            # 1分钟(测试)，单位毫秒
            x-message-ttl: 3000
        exchange:
          name: test

      # 死信队列
      - routing-key: dead
        consumer: deadConsumerService
        autoAck: false
        queue:
          name: dead
        exchange:
          name: dead

    host: xxx
    port: 5672
    username: rabbit
    password: 23Dl4uLzlJZVnIlbiyMd7AcR7kzrL4DG
    publisher-confirm-type: correlated
    virtual-host: /
    ssl:
      enabled: false
  # 国际化配置
#  messages:
#    basename: i18n/messages
#    encoding: UTF-8

springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
  api-docs:
    enabled: true


# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
#  setting:
#    # 设置界面语言
#    language: zh-CN
#    # 启用Swagger模型展示
#    enable-swagger-models: true
#    # 启用文档管理功能
#    enable-document-manage: true
#    # 启用OpenAPI 3.0的支持
#    enable-open-api: true
#    # 启用接口分组功能
#    enable-group: true



